# Generated by Django 4.1.7 on 2025-08-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_id',
            field=models.IntegerField(default=0, help_text='Порядковый номер беседы для пользователя'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['sub', 'conversation_id'], name='conversatio_sub_d3c8c4_idx'),
        ),
    ]
