# Generated by Django 4.1.7 on 2025-08-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddingdocument',
            name='document_id',
            field=models.IntegerField(default=0, help_text='Порядковый номер документа для пользователя'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(default=0, help_text='Порядковый номер сообщения для пользователя'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt_id',
            field=models.IntegerField(default=0, help_text='Порядковый номер промпта для пользователя'),
        ),
        migrations.AddIndex(
            model_name='embeddingdocument',
            index=models.Index(fields=['sub', 'document_id'], name='embedding_d_sub_fedc45_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sub', 'message_id'], name='messages_sub_c43b10_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['sub', 'prompt_id'], name='prompts_sub_12ff4e_idx'),
        ),
    ]
