# Generated by Django 4.1.7 on 2025-08-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_embeddingdocument_document_id_message_message_id_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_sub_509c75_idx',
            old_name='messages_sub_3e457c_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_convers_a3cf41_idx',
            old_name='messages_convers_3ebb41_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.IntegerField(help_text='Порядковый номер беседы для пользователя (conversation_id)'),
        ),
    ]
